### ISSUE TITLE
Divs should not be converted as <p>

### ISSUE THREAD

**Issue by tiberiuichim** [plone/blocks-conversion-tool#24] opened 2023-03-14 14:00 UTC
For a fragment such as `<div><h2>hello</h2></div>` the result should not be the equivalent of `<p><h2>hello</h2></p>`.

**Comment by davisagli** [comment] 2023-03-16 20:36
@tiberiuichim What are the steps to reproduce? I tried posting this:
```
{"html": "<div><h2>hello</h2></div>"}
```

And got this response:
```
{
    "data": [
        {
            "@type": "slate",
            "value": [
                {
                    "type": "h2",
                    "children": [
                        {
                            "text": "hello"
                        }
                    ]
                }
            ],
            "plaintext": "hello"
        }
    ]
}
```

Which looks fine.

It's quite possible the div isn't being handled correctly in some specific context, but then we need a complete example to investigate it. I'll close this since we have an example in #27 which shows some related issues with divs.

**Closed as not planned by davisagli** 2023-03-16 20:36 UTC
